# Setup
name:         Tech Medic
tagline:      Stopping the Bleeding of Bad Technical Decisions
baseurl:      ""
recentposts:  10

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
